### ISSUE TITLE
Client <unknown> disconnected due to malformed packet.

### ISSUE THREAD

**Issue by c64emulator** [alaub81/bsec_bme680-homie#1]
Hi,
I try to use your "bsec_bme680-homie" in a docker container.
The c_file compiled and runs, the "bsec_bme680.py" runs too.

Sending the output of "bsec_bme680" to mosquitto I test it first with
`./bsec_bme680 | mosquitto_pub -h 192.168.11.11 -u "mosquitto" -P "mosquitto" -p 1883 -t home/rpi4-test/bme680 -l` 
This is running with success. The MQTT Explorer is showing the received messages.

When trying to send the sensor data via python script to mosquitto fails. I get error:
```
root@a3355ac60597:/wrkdir/BME680/bsec_bme680-homie-main# python3 bsec_bme680-homie.py
Could not establish MQTT Connection! Try again 5x times
Could not establish MQTT Connection! Try again 4x times
Could not establish MQTT Connection! Try again 3x times
Could not establish MQTT Connection! Try again 2x times
Could not establish MQTT Connection! Try again 1x times
Could not connect to MQTT Broker! exit...
root@a3355ac60597:/wrkdir/BME680/bsec_bme680-homie-main# 
```
The mosquitto server is complaining in its log files too:
```
1651007467: mosquitto version 2.0.14 starting
1651007467: Config loaded from /mosquitto/config/mosquitto.conf.
1651007467: Opening ipv4 listen socket on port 1883.
1651007467: mosquitto version 2.0.14 running
:
1651011032: New connection from 172.17.0.4:40895 on port 1883.
1651011032: Client <unknown> disconnected due to malformed packet.

```
Any ideas?
Thank you for your work and friendly support.

**Comment by alaub81** [comment]
Hi!

could you please show me the configs of mosquito and of the python client script? Interesting is that the client shows up as `unknown`.

**Comment by c64emulator** [comment]
finally I was able to run the python client script and transfer the sensor data. I changed two lines, commenting the part for client.tls, see the snipped:
```
  try:
    client=mqtt.Client(mqttclientid)
    client.username_pw_set(username, password)
#    client.tls_set(cert_reqs=ssl.CERT_NONE) #no client certificate needed
#    client.tls_insecure_set(insecure)
    client.will_set("homie/" + clientid + "/$state","lost",qos,retain_message)
    client.connect(broker, port, 60)
```
May be this is a quick and dirty solution for my issue. But it runs...

The mosquitto config is fairly simple:
```
#port 1883
listener 1883 0.0.0.0
protocol mqtt

listener 9001 0.0.0.0
protocol websockets

persistence true
persistence_location /mosquitto/data

#allow_anonymous false
allow_anonymous true
#password_file /mosquitto/config/passwd
```

**Comment by alaub81** [comment]
yes. I thought about that. I am using MQTT over TLS so that's why it is not working without it. If you like to know how to use TLS Mosquito, have a look here: https://www.laub-home.de/wiki/Eclipse_Mosquitto_Secure_MQTT_Broker_Docker_Installation

**Comment by alaub81** [comment]
if you are fine with your solution just close the ticket. Thanks!

**Comment by c64emulator** [comment]
May be we should leave this as open issue for other people with same trouble?
